#!/bin/bash

if [[ -n $1 ]]; then
	USER="$1"
fi

source $(eval echo  "~$USER/.daynightrc") || exit
PERIOD=day

# Get day and hour
DAYS=$(date +"%j")
HOUR=$(date +"%H")

# Decide on wallpaper set based on daily rotation
WALLPAPER_NAME=${WALLPAPERS[$(($DAYS % ${#WALLPAPERS[@]}))]}
wallpaper "$WALLPAPER_PATH/$WALLPAPER_NAME-$PERIOD.$WALLPAPER_EXTENSION" $USER
