#!/bin/bash

# Optionally get user to work on
if [[ -n $2 ]]; then
	USER="$2"
fi

# Set wallpaper of user with DBus
sudo -u $USER \
DISPLAY=:0 \
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $USER)/bus \
qdbus org.kde.plasmashell /PlasmaShell evaluateScript '
    var allDesktops = desktops();
    for (i=0;i<allDesktops.length;i++)
    {
        d = allDesktops[i];
        d.wallpaperPlugin = "org.kde.image";
        d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");
        d.writeConfig("Image", "file://'$(realpath $1)'")
    }
'
